---
apiVersion: v1
kind: Namespace
metadata:
  name: bridge
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: da-bridge
    chain-id: private
    environment: private
    network: da
    type: bridge
  name: da-bridge
  namespace: bridge
spec:
  podManagementPolicy: OrderedReady
  replicas: 101
  revisionHistoryLimit: 10
  serviceName: da-bridge
  selector:
    matchLabels:
      app: da-bridge
      chain-id: private
      environment: private
      network: da
      type: bridge
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: da-bridge
        chain-id: private
        environment: private
        network: da
        type: bridge
    spec:
      containers:
      - command:
        - /home/celestia/start.sh
        env:
          #- name: CELESTIA_BOOTSTRAPPER
          #  value: "true"
        - name: GOLOG_LOG_FMT
          value: json
        - name: CELESTIA_HOME
          value: /home/celestia
        - name: CELESTIA_BIN_FOLDER
          value: /bin
        - name: CELESTIA_CUSTOM
          value: "private:38DF9533B8CF436D55252465550612603B3FB1D7124D3FF82005949681C2F684"
        - name: SETUP_PATH
          value: /tmp/celestia-config
            #- name: TRUSTED_PEERS
            #  valueFrom:
            #    configMapKeyRef:
            #      key: TRUSTED_PEERS
            #      name: trusted-peers
        image: ghcr.io/celestiaorg/celestia-node:v0.11.0-rc3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: rest
          timeoutSeconds: 1
        name: da
        ports:
        - containerPort: 2121
          name: p2p
          protocol: TCP
        - containerPort: 6060
          name: something-1
          protocol: TCP
        - containerPort: 26658
          name: rpc
          protocol: TCP
        - containerPort: 26659
          name: rest
          protocol: TCP
        - containerPort: 8890
          name: libp2p-metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: rest
          timeoutSeconds: 1
        resources:
          #limits:
          #  memory: 12Gi
          requests:
            cpu: "3"
            memory: 3Gi
        securityContext:
          runAsGroup: 10001
          runAsUser: 10001
        volumeMounts:
          #- mountPath: /home/celestia/config
          #  name: da-config
          #- mountPath: /home/celestia/data
          #  name: da-data
          #  subPath: data
          #- mountPath: /home/celestia/blocks
          #  name: da-data
          #  subPath: blocks
          #- mountPath: /home/celestia/index
          #  name: da-data
          #  subPath: index
          #- mountPath: /home/celestia/transients
          #  name: da-data
          #  subPath: transients
          #- mountPath: /home/celestia/keys
          #  name: da-keys
        - mountPath: /home/celestia/start.sh
          name: start
          subPath: start.sh
        - mountPath: /tmp/celestia-config
          name: shared
            #- command:
            #  - /otelcol-contrib
            #  - --config=/conf/otel-agent.yaml
            #  image: otel/opentelemetry-collector-contrib:0.71.0
            #  imagePullPolicy: IfNotPresent
            #  name: otel-agent
            #  ports:
            #  - containerPort: 8888
            #    name: prometheus-otel
            #    protocol: TCP
            #  - containerPort: 9090
            #    name: prometheus
            #    protocol: TCP
            #  resources:
            #    limits:
            #      memory: 200Mi
            #    requests:
            #      cpu: 100m
            #      memory: 100Mi
            #  volumeMounts:
            #  - mountPath: /conf/otel-agent.yaml
            #    #name: otel-agent–bridge
            #    name: otel-agent
            #    subPath: otel-agent.yaml
      dnsPolicy: ClusterFirst
        #initContainers:
        #- command:
        #  #- /setup/setup.sh
        #  - /setup/setup.sh
        #  env:
        #  - name: CELESTIA_BOOTSTRAPPER
        #    value: "true"
        #  - name: CONSENSUS_NODE_SERVICE
        #    value: consensus-full-1
        #  - name: CONSENSUS_NAMEPACE
        #    valueFrom:
        #      fieldRef:
        #        apiVersion: v1
        #        fieldPath: metadata.labels['consensus-namespace']
        #  - name: SETUP_PATH
        #    value: /tmp/celestia-config
        #  image: alpine:3.18.0
        #  imagePullPolicy: IfNotPresent
        #  name: da-setup
        #  resources:
        #    limits:
        #      memory: 500Mi
        #    requests:
        #      cpu: 300m
        #      memory: 250Mi
        #  terminationMessagePath: /dev/termination-log
        #  terminationMessagePolicy: File
        #  volumeMounts:
        #  - mountPath: /tmp/celestia-config
        #    name: shared
        #  - mountPath: /setup/setup.sh
        #    name: setup
        #    subPath: setup.sh
        #restartPolicy: Always
        #schedulerName: default-scheduler
        #securityContext:
        #  fsGroup: 10001
        #  fsGroupChangePolicy: OnRootMismatch
        #    #serviceAccount: da-sa-bridge
        #   
        #   
        #serviceAccountName: da-sa-bridge
        #terminationGracePeriodSeconds: 30
      volumes:
        #- configMap:
        #    defaultMode: 420
        #    name: otel-agent-bridge
        #  name: otel-agent
      - configMap:
          defaultMode: 0777
          name: start-bridge
        name: start
      - configMap:
          defaultMode: 360
          name: setup-bridge
        name: setup
      - emptyDir: {}
        name: shared
        #  name: otel-agent
        #- name: da-config
        #  persistentVolumeClaim:
        #    claimName: da-config-bridge
        #- name: da-data
        #  persistentVolumeClaim:
        #    claimName: da-data-bridge
        #- name: da-keys
        #  persistentVolumeClaim:
        #    claimName: da-keys-bridge
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
---
apiVersion: v1
data:
  start.sh: |
    #!/bin/bash
    celestia bridge init --node.store=/home/celestia/ && \
    sed -i "s|TrustedHash = \"\"|TrustedHash = \"38DF9533B8CF436D55252465550612603B3FB1D7124D3FF82005949681C2F684\"|g" /home/celestia/config.toml
    sed -i 's|MutualPeers = \[]|MutualPeers = \["/ip4/192.168.10.32/tcp/2121/p2p/12D3KooWHFDBoKECAPsJjBQGPn4WtKpPuJt9hsJgUHk6E1X1TRgD"]|g' /home/celestia/config.toml &&\
    cat /home/celestia/config.toml && \
    celestia bridge start --core.ip=100.65.58.158 --node.store=/home/celestia/ --gateway --metrics --metrics.tls=false --p2p.metrics --p2p.network=private --metrics.endpoint=otel.celestia.observer:4318 --pyroscope --pyroscope.tracing --pyroscope.endpoint http://pyroscope.pyroscope.svc.cluster.local:4040
kind: ConfigMap
metadata:
  labels:
    app: da-bridge
    chain-id: bridge
    type: bridge
  name: start-bridge
  namespace: bridge
