[metadata]
  name = "001-val-large-txs"
  author = "Bidon15"

[global]
  plan = "celestia"
  case = "001-val-large-txs"
  total_instances = 4
  builder = "docker:generic"
  runner = "local:docker"
  disable_metrics = false

[global.run.test_params]
  execution-time = "10"
  latency = "0"
  bandwidth = "320Mib"
  validator = "3"
  persistent-peers = "2"
  seed = "1"
  msg-size = "100000"

[[groups]]
  id = "validators"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""

[[groups]]
  id = "seeds"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""