[metadata]
  name = "003-full-sync-past-3-3-3-3-set"
  author = "Bidon15"

[global]
  plan = "celestia"
  case = "003-full-sync-past"
  total_instances = 13
  builder = "docker:generic"
  runner = "local:docker"
  disable_metrics = false

[global.run.test_params]
  execution-time = "30"
  persistent-peers = "2"
  submit-times = "42"
  msg-size = "100000"
  validator = "3"
  seed = "1"
  bridge = "3"
  full = "3"
  light = "3"

  [[groups]]
    id = "seeds"
    builder = "docker:generic"
    [groups.resources]
      memory = ""
      cpu = ""
    [groups.instances]
      count = 1
      percentage = 0.0
    [groups.build_config]
      build_base_image = "golang:1.19.1"
      enable_go_build_cache = true
      enabled = true
      go_version = "1.19"
    [groups.build]
    [groups.run]
      artifact = ""
    [groups.run.test_params]
      bandwidth = "256Mib"
      latency = "0"
      role = "seed"

[[groups]]
  id = "validators"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "0"
    bandwidth = "256Mib"
    role = "validator"

[[groups]]
  id = "bridges"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "0"
    bandwidth = "256Mib"
    block-height = "30"
    role = "bridge"

[[groups]]
  id = "fulls"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "0"
    bandwidth = "256Mib"
    block-height = "40"
    role = "full"

[[groups]]
  id = "lights"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "0"
    bandwidth = "100Mib"
    block-height = "40"
    role = "light"
