[metadata]
name = "reconstruction"
author = "Bidon15"

[global]
plan = "celestia"
case = "reconstruction"
total_instances = 372
builder = "docker:generic"
runner = "cluster:k8s"
disable_metrics = false
[global.run]
artifact = ""
[global.run.test_params]
bridge = "10"
execution-time = "40"
full = "2"
light = "350"
msg-size = "15000"
persistent-peers = "10"
submit-times = "60"
validator = "10"

[[groups]]
id = "validators"
builder = "docker:generic"
[groups.resources]
memory = "4Gi"
cpu = "2000m"
[groups.instances]
count = 10
percentage = 0.0
[groups.build_config]
build_base_image = "golang:1.20"
enable_go_build_cache = true
enabled = true
go_version = "1.20"
[groups.build]
[groups.run]
artifact = ""
[groups.run.test_params]
bandwidth = "256Mib"
latency = "50"
role = "validator"

[[groups]]
id = "bridges"
builder = "docker:generic"
[groups.resources]
memory = "3Gi"
cpu = "2000m"
[groups.instances]
count = 10
percentage = 0.0
[groups.build_config]
build_base_image = "golang:1.20"
enable_go_build_cache = true
enabled = true
go_version = "1.20"
[groups.build]
[groups.run]
artifact = ""
[groups.run.test_params]
bandwidth = "256Mib"
block-height = "5"
latency = "50"
role = "bridge"

[[groups]]
id = "fulls"
builder = "docker:generic"
[groups.resources]
memory = "4Gi"
cpu = "3"
[groups.instances]
count = 2
percentage = 0.0
[groups.build_config]
build_base_image = "golang:1.20"
enable_go_build_cache = true
enabled = true
go_version = "1.20"
[groups.build]
[groups.run]
artifact = ""
[groups.run.test_params]
bandwidth = "256Mib"
block-height = "5"
latency = "50"
role = "full"

[[groups]]
id = "lights"
builder = "docker:generic"
[groups.resources]
memory = "400Mi"
cpu = "1000m"
[groups.instances]
count = 350
percentage = 0.0
[groups.build_config]
build_base_image = "golang:1.20"
enable_go_build_cache = true
enabled = true
go_version = "1.20"
[groups.build]
[groups.run]
artifact = ""
[groups.run.test_params]
bandwidth = "256Mib"
block-height = "5"
latency = "50"
role = "light"
