apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana-external
  namespace: default
    #namespace: monitoring
  annotations:
  labels:
    app.kubernetes.io/instance: monitoring-stack
    app.kubernetes.io/name: grafana
spec:
  selector:
    app.kubernetes.io/instance: monitoring-stack
    app.kubernetes.io/name: grafana
  type: LoadBalancer
  ports:
    - name: http-web
      port: 80
      protocol: TCP
      targetPort: 3000
