[metadata]
  name = "flood-arabica-201"
  author = "Bidon15"

[global]
  plan = "celestia"
  case = "flood-arabica"
  total_instances = 201
  builder = "docker:generic"
  runner = "cluster:k8s"
  disable_metrics = false
  [global.run]
    artifact = ""
    [global.run.test_params]
      execution-time = "20"
      light = "140"


[[groups]]
  id = "lights"
  builder = "docker:generic"
  [groups.resources]
    memory = "300Mi"
    cpu = "100m"
  [groups.instances]
    count = 200
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bandwidth = "100Mib"
      block-height = "10000"
      latency = "0"
      role = "light"

[[groups]]
id = "fulls"
builder = "docker:generic"
[groups.resources]
memory = "8000Mi"
cpu = "6000m"
[groups.instances]
count = 1
percentage = 0.0
[groups.build_config]
build_base_image = "golang:1.19.1"
enable_go_build_cache = true
enabled = true
go_version = "1.19"
[groups.build]
[groups.run]
artifact = ""
[groups.run.test_params]
bandwidth = "256Mib"
block-height = "10000"
latency = "0"
role = "full"