[metadata]
  name = "blocksyncbench-historical"
  author = "derrandz"

[global]
  plan = "celestia"
  case = "blocksyncbench-historical"
  total_instances = 37
  builder = "docker:generic"
  runner = "cluster:k8s"
  disable_metrics = false

# we define 1 validator that produces 8mb blocks
# the msg-size does not result in exactly 8mb
# because we are accounting for padding
[global.run.test_params]
  execution-time = "20"
  persistent-peers = "1"
  msg-size = "800000"
  validator = "1"
  bridge = "4"
  full = "32"
  block-height = "100"
  target-height = "70"
  otel-collector-address = "178.128.163.171:4318"
  getter = "ipld"
  hiccup-height = "10"
  fullnode-entrypoints = "3"
  bridgenode-entrypoints = "1"

[[groups]]
  id = "validators"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "1"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "50"
    bandwidth = "256Mib"
    role = "validator"

[[groups]]
  id = "bridges"
  builder = "docker:generic"
  [groups.resources]
    memory = "8Gi"
    cpu = "1"
  [groups.instances]
    count = 4
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "50"
    bandwidth = "256Mib"
    role = "bridge"

[[groups]]
  id = "fulls"
  builder = "docker:generic"
  [groups.resources]
    memory = "8Gi"
    cpu = "1"
  [groups.instances]
    count = 32
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "50"
    bandwidth = "256Mib"
    role = "full"
