[metadata]
  name = "pay-for-data-100-100-1000-set"
  author = "Bidon15"

[global]
  plan = "celestia"
  case = "pay-for-blob"
  total_instances = 325
  builder = "docker:generic"
  runner = "cluster:k8s"
  disable_metrics = false
  [global.run]
    artifact = ""
    [global.run.test_params]
      execution-time = "25"
      msg-size = "4800"
      namespace-id = "random"
      persistent-peers = "10"
      seed = "5"
      validator = "100"
      bridge = "100"
      light = "120"
      submit-times = "5"

[[groups]]
  id = "seeds"
  builder = "docker:generic"
  [groups.resources]
    memory = "2Gi"
    cpu = "2"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bandwidth = "256Mib"
      latency = "0"
      role = "seed"

[[groups]]
  id = "validators"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "3500m"
  [groups.instances]
    count = 100
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bandwidth = "320Mib"
      latency = "0"
      role = "validator"

[[groups]]
  id = "bridges"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "3000m"
  [groups.instances]
    count = 100
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bandwidth = "320Mib"
      block-height = "30"
      latency = "0"
      role = "bridge"

[[groups]]
  id = "lights"
  builder = "docker:generic"
  [groups.resources]
    memory = "300Mi"
    cpu = "200m"
  [groups.instances]
    count = 100
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bandwidth = "100Mib"
      block-height = "16"
      latency = "0"
      role = "light"

[[groups]]
id = "lights-nodas"
builder = "docker:generic"
[groups.resources]
memory = "300Mi"
cpu = "200m"
[groups.instances]
count = 20
percentage = 0.0
[groups.build_config]
build_base_image = "golang:1.19.1"
enable_go_build_cache = true
enabled = true
go_version = "1.19"
[groups.build]
[groups.run]
artifact = ""
[groups.run.test_params]
bandwidth = "100Mib"
block-height = "16"
latency = "0"
role = "light"
