[metadata]
  name = "flood-robusta-nightly-1"
  author = "Bidon15"

[global]
  plan = "celestia"
  case = "flood-robusta-nightly-1"
  total_instances = 11
  builder = "docker:generic"
  runner = "cluster:k8s"
  disable_metrics = false
  [global.run]
    artifact = ""
    [global.run.test_params]
      execution-time = "20"

[[groups]]
  id = "lights"
  builder = "docker:generic"
  [groups.resources]
    memory = "100Mi"
    cpu = "100m"
  [groups.instances]
    count = 10
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.20-alpine3.17"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.20.3"
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bandwidth = "100Mib"
      block-height = "10000"
      latency = "0"
      role = "light"

[[groups]]
  id = "fulls"
  builder = "docker:generic"
[groups.resources]
  memory = "4Gi"
  cpu = "2000m"
[groups.instances]
  count = 1
  percentage = 0.0
[groups.build_config]
  build_base_image = "golang:1.20-alpine3.17"
  enable_go_build_cache = true
  enabled = true
  go_version = "1.20.3"
[groups.build]
[groups.run]
  artifact = ""
  [groups.run.test_params]
    bandwidth = "256Mib"
    block-height = "10000"
    latency = "0"
    role = "full"
