{
 "title": "Cosmos/Tendermint Network Influx",
 "tags": [
  "Testing",
  "InfluxDB"
 ],
 "time": { "from": "2023-02-22T10:07:31.237Z", "to": "2023-02-22T10:18:28.912Z" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "influxdb" },
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": "show tag values from \"tendermint_p2p_peers\" with key = \"chain_id\""
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "show tag values from \"tendermint_p2p_peers\" with key = \"host\""
   }
  ]
 },
 "panels": [
  { "title": "TL;DR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Validators",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Active",
     "measurement": "tendermint_consensus_validators",
     "query": "SELECT \"gauge\" FROM \"tendermint_consensus_validators\" WHERE (\"host\" =~ /^$instance$/)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "expr": "tendermint_consensus_missing_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Missing",
     "query": "SELECT \"gauge\" FROM \"tendermint_consensus_missing_validators\" WHERE (\"host\" =~ /^$instance$/)"
    },
    {
     "expr": "tendermint_consensus_byzantine_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Byzantine",
     "query": "SELECT \"gauge\" FROM \"tendermint_consensus_byzantine_validators\" WHERE (\"host\" =~ /^$instance$/)"
    }
   ]
  },
  {
   "title": "$chain_id network overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "tendermint_consensus_height",
     "query": "SELECT \"gauge\" FROM \"tendermint_consensus_height\" WHERE (\"host\" =~ /^$instance$/) ",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Total tendermint Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tendermint_consensus_total_txs",
     "query": "SELECT \"gauge\" FROM \"tendermint_consensus_total_txs\" WHERE (\"host\" =~ /^$instance$/)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "tendermint_consensus_block_interval_seconds",
     "query": "SELECT \"sum\", \"count\" FROM \"tendermint_consensus_block_interval_seconds\" WHERE (\"host\" =~ /^$instance$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Block Size",
     "query": "SELECT \"gauge\" FROM \"tendermint_consensus_block_size_bytes\" WHERE (\"host\" =~ /^$instance$/)"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tendermint_consensus_num_txs{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Transactions",
     "query": "SELECT \"gauge\" FROM \"tendermint_consensus_num_txs\" WHERE (\"host\" =~ /^$instance$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Mempool Already Seen TXs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "SELECT \"counter\" FROM \"tendermint_mempool_already_seen_txs\" WHERE (\"host\" =~ /^$instance$/)"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "SELECT \"gauge\" FROM \"tendermint_mempool_size\" WHERE (\"host\" =~ /^$instance$/)"
    }
   ]
  },
  {
   "title": "Mempool TX Size in Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "SELECT * FROM \"tendermint_mempool_tx_size_bytes\" WHERE (\"host\" =~ /^$instance$/)"
    }
   ]
  },
  {
   "title": "Tendermint instance overview + P2P: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT \"gauge\" FROM \"tendermint_p2p_peers\" WHERE (\"host\" =~ /^$instance$/)"
    }
   ]
  },
  {
   "title": "Is fast syncing ?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"gauge\" FROM \"tendermint_consensus_fast_syncing\" WHERE (\"host\" =~ /^$instance$/)"
    }
   ]
  },
  {
   "title": "Is state syncing ?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"gauge\" FROM \"tendermint_consensus_state_syncing\" WHERE (\"host\" =~ /^$instance$/)"
    }
   ]
  },
  {
   "title": "Consensus Rounds",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT \"gauge\" FROM \"tendermint_consensus_rounds\" WHERE (\"host\" =~ /^$instance$/)"
    }
   ]
  },
  {
   "title": "Send Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT * FROM \"tendermint_p2p_peer_send_bytes_total\" WHERE (\"host\" =~ /^$instance$/)"
    }
   ]
  }
 ]
}