apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: otel-collector-pod-monitor
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: opentelemetry
  podMetricsEndpoints:
    - port: otlp-exporter