---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: da-light-89
    chain-id: private
    environment: private
    network: da
    type: light
  name: da-light-89
  namespace: light
spec:
  replicas: 56
  #serviceName: da-light-89
  selector:
    matchLabels:
      app: da-light-89
      chain-id: private
      environment: private
      network: da
      type: light
  strategy: {}
  template:
    metadata:
      labels:
        app: da-light-89
        chain-id: private
        environment: private
        network: da
        type: light
    spec:
      nodeSelector:
        kops.k8s.io/instancegroup: light
      containers:
        - command:
            - /home/celestia/start.sh
          env:
            #- name: CELESTIA_BOOTSTRAPPER
            #  value: "true"
            - name: GOLOG_LOG_FMT
              value: json
            - name: CELESTIA_HOME
              value: /home/celestia
            - name: CELESTIA_BIN_FOLDER
              value: /bin
            - name: CELESTIA_CUSTOM
              value: "private:500DEFD029C60703765BBC188948CDC4AA7B99605E780D1685BCEF6252C17D08"
            - name: SETUP_PATH
              value: /tmp/celestia-config
                #- name: TRUSTED_PEERS
                #  valueFrom:
                #    configMapKeyRef:
              #      key: TRUSTED_PEERS
              #      name: trusted-peers
          image: ghcr.io/celestiaorg/celestia-node:403eb61
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: rest
            timeoutSeconds: 1
          name: da
          ports:
            - containerPort: 2121
              name: p2p
              protocol: TCP
            - containerPort: 6060
              name: something-1
              protocol: TCP
            - containerPort: 26658
              name: rpc
              protocol: TCP
            - containerPort: 26659
              name: rest
              protocol: TCP
            - containerPort: 8890
              name: libp2p-metrics
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: rest
            timeoutSeconds: 1
          resources:
           #limits:
            #  memory: 250Mi
            requests:
              cpu: "100m"
              memory: 200Mi
          securityContext:
            runAsGroup: 10001
            runAsUser: 10001
          volumeMounts:
            #- mountPath: /home/celestia/config
            #  name: da-config
            #- mountPath: /home/celestia/data
            #  name: da-data
            #  subPath: data
            #- mountPath: /home/celestia/blocks
            #  name: da-data
            #  subPath: blocks
            #- mountPath: /home/celestia/index
            #  name: da-data
            #  subPath: index
            #- mountPath: /home/celestia/transients
            #  name: da-data
            #  subPath: transients
            #- mountPath: /home/celestia/keys
            #  name: da-keys
            - mountPath: /home/celestia/start.sh
              name: start
              subPath: start.sh
            - mountPath: /tmp/celestia-config
              name: shared
      #- command:
      #  - /otelcol-contrib
      #  - --config=/conf/otel-agent.yaml
      #  image: otel/opentelemetry-collector-contrib:0.71.0
      #  imagePullPolicy: IfNotPresent
      #  name: otel-agent
      #  ports:
      #  - containerPort: 8888
      #    name: prometheus-otel
      #    protocol: TCP
      #  - containerPort: 9090
      #    name: prometheus
      #    protocol: TCP
      #  resources:
      #    limits:
      #      memory: 200Mi
      #    requests:
      #      cpu: 100m
      #      memory: 100Mi
      #  terminationMessagePath: /dev/termination-log
      #  terminationMessagePolicy: File
      #  volumeMounts:
      #  - mountPath: /conf/otel-agent.yaml
      #    name: otel-agent
      #    subPath: otel-agent.yaml
      dnsPolicy: ClusterFirst
        #initContainers:
        #- command:
        #  #- /setup/setup.sh
        #  - /setup/setup.sh
        #  env:
        #  - name: CELESTIA_BOOTSTRAPPER
        #    value: "true"
        #  - name: CONSENSUS_NODE_SERVICE
        #    value: consensus-full-1
        #  - name: CONSENSUS_NAMEPACE
        #    valueFrom:
        #      fieldRef:
        #        apiVersion: v1
        #        fieldPath: metadata.labels['consensus-namespace']
        #  - name: SETUP_PATH
        #    value: /tmp/celestia-config
        #  image: alpine:3.18.0
        #  imagePullPolicy: IfNotPresent
        #  name: da-setup
        #  resources:
        #    limits:
        #      memory: 500Mi
        #    requests:
        #      cpu: 300m
        #      memory: 250Mi
        #  terminationMessagePath: /dev/termination-log
        #  terminationMessagePolicy: File
        #  volumeMounts:
        #  - mountPath: /tmp/celestia-config
        #    name: shared
        #  - mountPath: /setup/setup.sh
        #    name: setup
        #    subPath: setup.sh
        #restartPolicy: Always
        #schedulerName: default-scheduler
        #securityContext:
        #  fsGroup: 10001
        #  fsGroupChangePolicy: OnRootMismatch
        #    #serviceAccount: da-sa-bridge-1
      #    #serviceAccountName: da-sa-bridge-1
      #terminationGracePeriodSeconds: 30
      volumes:
        #- configMap:
        #    defaultMode: 420
        #    name: otel-agent-bridge-1-gb2ct8d928
        #  name: otel-agent
        #- name: da-config
        #  persistentVolumeClaim:
        #    claimName: da-config-bridge-1
        #- name: da-data
        #  persistentVolumeClaim:
        #    claimName: da-data-bridge-1
        #- name: da-keys
        #  persistentVolumeClaim:
        #    claimName: da-keys-bridge-1
        - configMap:
            defaultMode: 0777
            name: start-light-89
          name: start
        - configMap:
            defaultMode: 360
            name: setup-light-89
          name: setup
        - emptyDir: {}
          name: shared
---
apiVersion: v1
data:
  start.sh: |
    #!/bin/bash
    celestia light init --node.store=/home/celestia/
    sed -i "s|TrustedHash = \"\"|TrustedHash = \"500DEFD029C60703765BBC188948CDC4AA7B99605E780D1685BCEF6252C17D08\"|g" /home/celestia/config.toml # consensus first hash
    # BN, FN, Bootstrapper
    sed -i 's|TrustedPeers = \[]|TrustedPeers = \["/ip4/100.96.86.106/tcp/2121/p2p/12D3KooWK8J7SCv96xm3kLG15DgcuXnihztJhV3dZvYN3ks8DFHt","/ip4/100.96.142.174/tcp/2121/p2p/12D3KooWJMRfAifkqdztJMNFzS7Rje68YNFTxLX1R7xifVDJyfi6","/ip4/100.96.86.67/tcp/2121/p2p/12D3KooWMA5Sm6fn4U5nCJfcRkVrHBRE2NXZC11hoUoBEP747M5S"]|g' /home/celestia/config.toml
    cat /home/celestia/config.toml
    celestia light start --core.ip=100.66.39.25  --node.store=/home/celestia/ --gateway --metrics --metrics.tls=false --p2p.metrics --p2p.network=private --metrics.endpoint=otel.celestia.observer:4318  --pyroscope --pyroscope.tracing --pyroscope.endpoint http://pyroscope.pyroscope.svc.cluster.local:4040
kind: ConfigMap
metadata:
  labels:
    app: da-light-89
    chain-id: light
    type: light
  name: start-light-89
  namespace: light
